### PR TITLE
File to store characteristics for determining ACIS FP data quality limits

### PR DESCRIPTION
**Pull request by jzuhone**
This PR introduces a new characteristics file for the ACIS FP temperature limit, containing the numerical values which determine to what FP temperature specific observations are allowed to go to. 

Submitted in support of https://github.com/sot/chandra_limits/issues/2, but a corresponding change to `chandra_limits` that uses this file also needs to be prepared (in work).

### CODE REVIEW

**Comment by jeanconn** [comment]
I haven't been paying quite enough attention, but naively I wonder if these pars should all be in a subsection and have an id that ties them over to the model limit in the model spec file by planning limit name.  I don't know if that would be over-configured, but it seems like there a decent chance you could add another limit with similar-but-different parameters.

**Comment by jzuhone** [comment]
Hi @jeanconn,

>  I wonder if these pars should all be in a subsection

A subsection of the same file, where each section name is a limit, or something else?

> it seems like there a decent chance you could add another limit with similar-but-different parameters.

Right now these parameters all refer to separate limits and I'm actually not sure how to predict how things could translate to different limits. It seems like the sort of bridge we'd have to cross when we got to it.

**Comment by jeanconn** [comment]
> A subsection of the same file, where each section name is a limit, or something else?

Yes.  That's what I was thinking.  I wasn't sure if something that tied the the limit to the conditions made sense, like... (I think I have this logic wrong but you probably see better what I meant).

```
aciss_hot:
  limit: 'planning.data_quality.high.aciss_hot'
  spectral_max_count: # the maximum number of counts for hot ACIS observations
    acis_i: 1000.0
    acis_s: 2000.0
  num_counts: 300 # fallback criterion for the number of expected counts for hot ACIS observations
  hetg_simz: -6.0 # the SIM-Z in mm less than which we can go to very hot temperatures
```

But it sounds like it makes the most sense to start with what you have instead of trying to guess what other configurations could exist in the future for this etc.

**Comment by taldcroft** [comment]
Following on from @jeanconn's comment, one possibility would be to make this be the start of a generic ACIS characteristics file for parameters that should be FSDS controlled [1]. So basically a new directory `acis/` for all things ACIS and a new file `acis/characteristics.yml` to store parameters. 

I'm also OK with the current PR which is more of a one-file-per-topic plan. Your call.

[1] - meaning they might change one day and it would be convenient to change without a Ska release.

**Comment by jzuhone** [comment]
@taldcroft @jeanconn good suggestion--check out the latest version.

**Comment by jeanconn** [comment]
@taldcroft would yml files in chandra_models suggest that we'd want add something in ska_helpers.chandra_models to handle those too?

**Comment by taldcroft** [comment]
@jeanconn - what do you mean by "handle"? What's wrong with getting the data as a string and parsing the YAML?

**Review by taldcroft — APPROVED** [review]
Looks good to me.

**Comment by jeanconn** [comment]
"@jeanconn - what do you mean by "handle"? What's wrong with getting the data as a string and parsing the YAML?"

My mistake, I thought ska_helpers.chandra_models.get_data was parsing the json of the other models .  I must have remembered something incorrectly with regard to read_func .

**Review by jeanconn — APPROVED** [review]

**Review by matthewdahmer — APPROVED** [review]

**Pull request merged**
