### PR TITLE
Add files for the pitch-roll constraint

### LINKED ISSUE #102: Add pitch roll constraint data to chandra_models

### PR DESCRIPTION
**Pull request by taldcroft**
This is part of updating the Ska sun-pitch roll constraint as implemented in `ska_sun.allowed_rolldev()`. It includes the new restricted pitch-roll constraint following degradation of the FSS-B around 2023:044.

Idiomatic use of this new data file will rely on https://github.com/sot/ska_helpers/pull/32.

Fixes #102

### CODE REVIEW

**Comment by taldcroft** [comment]
One question is whether the value should be 0 for pitch >= 178.0. Right now it is 18.5 right up to 180.0.

**Comment by jeanconn** [comment]
Seems like allowed pitch should be a separate table?

**Comment by taldcroft** [comment]
Thinking more, from a spacecraft perspective a roll of 15 at a pitch angle of 179.9 is just fine. So I'll go with what's here. 

Constraints on pitch are not in the scope of this PR, this is off_nom_roll as a function of pitch.

**Comment by jeanconn** [comment]
Fine to consider it out of scope for this PR, I was really just working from the title and wondering if including the pitch constraint it would remove ambiguity (then maybe you'd return nan if outside the range... but then again maybe not).  For the allowed pitch, previously I cared when developing yoshi for example and wondered if one new SOT characteristics reference would have value here, but we don't really have any ACA applications that need the allowed pitch range now.

**Comment by taldcroft** [comment]
@jeanconn - I updated the data file to have a point with -1.000 on each end, with the final pitch point at 178.0. This does a few things:
- In encapsulates the allowed pitch range for planning as the first and last pitch values in the table, accurate to within 3e-14 deg (which is good enough in practice). This convention is clearly documented in the README.
- Removes a potential source of ambiguity in checking the values. An application might naively apply the constraint `abs(computed_off_nom_roll) <= allowed_off_nom_roll` and find that pitch of 45.0 is fine for `off_nom_roll = 0.0`. So this new convention precludes any such situation.
- It allows sampling the allowed roll range using `np.linspace(-allowed_rolldev, +allowed_rolldev, n_samples)`.

**Comment by matthewdahmer** [comment]
Is this file as written in this repository defining the allowed pitch-roll envelope expected to be used by the FOT Tools, in such a way that it replaces the current definition in the FOT Tools? (tagging @jskrist)

**Comment by jskrist** [comment]
Short answer, no. The source data for this new file is still in the FOT MATLAB Tools and shall remain there (for now at least). I don't plan to replace it with this new feature from Python, as the infrastructure in MATLAB is easier to use/modify at the moment.

**Comment by jeanconn** [comment]
One more comment... if we ended up with an asymmetric update to this, we'd need more code changes.  Seems fine for now.

**Comment by jeanconn** [comment]
New table seems reasonable by inspection as called from the ska_sun PR https://github.com/sot/ska_sun/pull/27
pitch-roll

**Comment by taldcroft** [comment]
@jeanconn - anything more on this?

**Comment by jeanconn** [comment]
I didn't approve just because I was trying to figure out if the Windows testing you'd mentioned in the ska_helpers PR should happen as a pre-merge thing or as an integration test.

**Review by jeanconn — APPROVED** [review]

**Comment by taldcroft** [comment]
Testing on Windows will be much easier with an rc release. We just need to remember to run unit tests on Windows.

**Pull request merged**
