### PR TITLE
Update ACIS FP model to account for DH heater

### PR DESCRIPTION
**Pull request by taldcroft**
This model update corresponds to the file created by @Gregg140 for the corresponding update to the ACIS FP load review tool.  The only functional change here is in the ThermostatHeater `T_set` parameter from -120.0 to -119.9.  This makes no significant difference in model output.

MD5sum: `be72d3f58fbcff994ab67cb55fb5a5a3` :  chandra_models/xija/acisfp/acisfp_spec.json`

Permalink from commit:
https://github.com/sot/chandra_models/blob/1105670/chandra_models/xija/acisfp/acisfp_spec.json
cc: @mdahmer

### CODE REVIEW

**Comment by taldcroft** [comment]
Sorry, wrong username above.

cc: @matthewdahmer

**Comment by mbaski** [comment]
If there is no significant change in the output of the model, what is the purpose of the change (and is it worth it to implement and test it in the MATLAB Tools)?

**Comment by taldcroft** [comment]
The new model spec does include `bad_times` values which help in calibration and looking at historical data.  I agree that for the actual model parameters it would be fine to stay with the current version as of the 0.7 release.

`bad_times` is a model-specific list of time intervals that should be ignored in the calibration (fitting) process.  I'm open to ideas for how to manage this information in a way that doesn't drive unnecessary version updates.  I think this change is a bit of an oddball in not updating the functional model calibration, most of the time I would expect to update the calibration as long as we're at it.  I'll ask Gregg.

**Comment by taldcroft** [comment]
@matthewdahmer @mbaski - with concurrence from @Gregg140 and ACIS ops, I've updated the model spec file in commit 1105670.  I also updated the SHA reference and the MD5sum in the PR summary up  top.

**Comment by taldcroft** [comment]
Approved by TWG on 2015-Dec-15.

**Pull request merged**
