### PR TITLE
Updating PSMC model fit

### PR DESCRIPTION
**Pull request by jazan12**
Update to PSMC thermal model fit with bias and solar minimum coefficients zeroed out.

### CODE REVIEW

**Comment by Gregg140** [comment]
Can you please post some before and after dashboard plots? Not a whole lot can be checked by just looking at changes to a JSON file.

**Comment by jazan12** [comment]
[PSMC_update_020420.pdf](https://github.com/sot/chandra_models/files/4154930/PSMC_update_020420.pdf)

Adding the TWG presentation showing improvements associated with the model update.

**Comment by jeanconn** [comment]
I suppose I did forget to ask, I assume the dashboard plots and such were run with xija 4.16?  We've still got xija 4.15 in ska3-matlab.  I think this should not make a difference for the psmc model (dt=328) and I think our current process is that @matthewdahmer will verify all looks "expected".

**Comment by jazan12** [comment]
re: Jean, Just checked and the fits and plots were using xija 4.15

**Comment by matthewdahmer** [comment]
I have checked that the model performance matches the model presented (using xija 4.15). I also checked that the md5 sum matches the sum posted to the TWiki. This model looks good to go, thank you!

**Comment by matthewdahmer** [comment]
@jazan12 the version tag should be incremented to 3.28. I can merge and then update the version myself, however it would be a little cleaner if you update this on your side.

**Comment by jazan12** [comment]
Hey Matt,

OK, just made that edit.  Thanks,

-Jack

**Pull request merged**
