### PR TITLE
Use fully-qualified dates for epoch times

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

Starting with Chandra.Time version 4.0, dates like `2010:001` will represent midnight of that day, not noon.  This PR makes all `YYYY:DDD` dates (typically epoch times) in the xija models use a fully-qualified form `YYYY:DDD:12:00:00`. This corresponds to the pre-4.0 default and will allow regression tests to continue passing when Chandra.Time 4.0 is promoted to flight.

## Testing

See `compare_xija_model_output.py.txt` in attachments of https://occweb.cfa.harvard.edu/twiki/bin/view/ThermalWG/MeetingNotes2020x08x04. All models show zero difference.

## Review and approval

Reviewed and approved by [TWG on 2020-08-04](https://occweb.cfa.harvard.edu/twiki/bin/view/ThermalWG/MeetingNotes2020x08x04)

### CODE REVIEW

**Comment by taldcroft** [comment]
@matthewdahmer @jzuhone - I'd like to bring this to TWG next week to be in a good position for shiny. The 12-hour diffs in epoch times are small but can cause regression test fails. I was seeing noticeable regressions in starcheck thermal output for shiny and I'm wondering if it was from this.

**Comment by matthewdahmer** [comment]
I don't see why we can't review it at next week's TWG. I can generate a script to compare the output from both xija+chandra_models libraries.

**Comment by matthewdahmer** [comment]
@taldcroft, the DEA model in this PR is now out of date. I can post a revised copy directly if you would like. All other models in this PR show zero difference with their current production versions.

**Comment by taldcroft** [comment]
@matthewdahmer - I rebased this on master so it should have all the latest model specs.

**Comment by matthewdahmer** [comment]
@taldcroft I incremented the version so we can generate a new release and test in Matlab.

**Pull request merged**
