### PR TITLE
Pitch roll constraint from Matlab tools 2023_020

### PR DESCRIPTION
**Pull request by taldcroft**
This updates the pitch / roll constraint file to match the values in the `2023_coming_pitch_roll.csv` attachment of the MPCWG 2023x06x01 Twiki meeting notes page. Two slight modifications were introduced:

Added a `pitch,off_nom_roll` header line to define column names

Ensured that the curve is single-valued by adding a very small offset to the second pitch (x-axis) value in places where there were duplicates. This is fairly obvious looking at the file. This change is needed for the current flight version of SOT tools (`ska_sun.allowed_rolldev`) which uses this file, but a pending version lifts this restriction.

In practice duplicate values don't really matter, but from a code perspective the question is (e.g.) what should be the allowed off nominal roll at exactly 85.5 deg pitch. Is it 17.5 or 12.436?

### CODE REVIEW

**Review by matthewdahmer — APPROVED** [review]

**Comment by jeanconn** [comment]
The last time we did this, @jskrist made changes to the script that was used to generate the date to have unique pitch values for each row, so my impression was that largely we were delegating to the FOT to ... disambiguate?  In practice, it seems fine to have a couple of tiny modifications from the reference file given the use cases of this file.

**Comment by taldcroft** [comment]
Sounds good. I'll change to an epsilon of exactly 3e-14 since that is what is significant to 64-bit floating precision.
```
In [24]: print(178.0 + np.spacing(178.0))
178.00000000000003

In [25]: 178.00000000000003 == 178.000000000000031
Out[25]: True

In [26]: 178.00000000000003 == 178.00000000000002
Out[26]: True

In [27]: 178.00000000000003 == 178.00000000000001
Out[27]: False

In [28]: 178.00000000000003 == 178.00000000000000
Out[28]: False
```

**Comment by taldcroft** [comment]
No wait, I'll use `val + np.spacing(val)` in each case.

**Comment by taldcroft** [comment]
Here is my validation for Python:
```
In [1]: from astropy.table import Table

In [2]: t = Table.read("pitch_roll_constraint.csv")

In [3]: assert np.all(np.diff(t["pitch"]) > 0.0)

In [4]: np.all(np.diff(t["pitch"]) > 0.0)
Out[4]: True

In [5]: np.min(np.diff(t["pitch"]))
Out[5]: 1.4210854715202004e-14
```

**Review by jeanconn — APPROVED** [review]
LGTM

**Pull request merged**
