### PR TITLE
Add ACA acquisition probability models

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

This adds data files for the ACA acquisition probability model that gets used in `chandra_aca.star_probs`.

## Testing

See https://github.com/sot/chandra_aca/pull/140

### CODE REVIEW

**Review by jeanconn — APPROVED** [review]
This makes sense to me (as an independent PR that we can review and merge before the new model).

**Comment by matthewdahmer** [comment]
Do we need to increment the version for this and does this change require a Jira ticket?

**Comment by jeanconn** [comment]
I would figure we would just bother to increment the version on the "other" PR that will have the update to the model.

**Comment by matthewdahmer** [comment]
Including this PR in the upcoming release works for me as long as this PR can be merged in time with the ACA model update. If this PR affects a flight approved process upon promotion it should be accompanied by a Jira ticket though, and the ACA model is just about ready for promotion (all non FD approvals are in).

**Comment by jeanconn** [comment]
And with regard to "update to the model" I was speaking to the update to the acquisition probability model not the update to the aca thermal model.  I leave it to Tom to say if he wants to get this in to the ACA thermal model update release.

**Comment by taldcroft** [comment]
Since these new files don't yet impact any flight-approved process I think we can just merge this without additional review. Does it make life simpler if we hold off on merging until version 3.46 is approved and deployed (FSDS-62)? There is really no urgency on this one apart from making review of other Ska PR's a little easier.

**Comment by matthewdahmer** [comment]
In that case there is no issue with merging this in at any time, thank you!

**Review by matthewdahmer — APPROVED** [review]

**Pull request merged**
